name: haskell-poker
version: "0.0.0"
dependencies:
  - base >=4.9.1.0 && <5
  - random
  - random-shuffle
library:
  source-dirs: lib
  ghc-options:
  - -Wall
  - -fwarn-tabs

executables:
  haskell-poker:
    main: Main.hs
    source-dirs: app

    dependencies:
      - haskell-poker
tests:
  haskell-poker-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - haskell-poker
      - hspec
